<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC-20190429PFOY" ignored="0" name="Test(failed)" tests="5" failures="3" timestamp="08 二月 2020 15:30:38 GMT" time="0.062" errors="0">
  <testcase name="f" time="0.024" classname="com.testing.runner.dataDriven">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.004" classname="com.testing.runner.dataDriven">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.004" classname="com.testing.runner.dataDriven">
    <failure type="java.lang.AssertionError" message="expected [pass] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [fail]
at com.testing.runner.dataDriven.f(dataDriven.java:43)
at com.testing.runner.RunTestNG.main(RunTestNG.java:28)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.004" classname="com.testing.runner.dataDriven">
    <failure type="java.lang.AssertionError" message="expected [pass] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [fail]
at com.testing.runner.dataDriven.f(dataDriven.java:43)
at com.testing.runner.RunTestNG.main(RunTestNG.java:28)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.005" classname="com.testing.runner.dataDriven">
    <failure type="java.lang.AssertionError" message="expected [pass] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [fail]
at com.testing.runner.dataDriven.f(dataDriven.java:43)
at com.testing.runner.RunTestNG.main(RunTestNG.java:28)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- f -->
</testsuite> <!-- Test(failed) -->
